-- Comunio catalog + per-user squad. Paste in Supabase SQL editor or: supabase db push

create table public.player (
  id integer generated by default as identity primary key,
  name text not null,
  position text,
  verein text,
  aktueller_marktwert integer,
  transfermarkt_id integer unique
);

create table public.fixture (
  id integer generated by default as identity primary key,
  spieltag integer not null,
  heim_verein text not null,
  auswaerts_verein text not null,
  datum timestamptz not null
);

create table public.value_history (
  id integer generated by default as identity primary key,
  player_id integer not null references public.player (id) on delete cascade,
  datum date not null,
  marktwert integer,
  unique (player_id, datum)
);

create table public.rating_history (
  id integer generated by default as identity primary key,
  player_id integer not null references public.player (id) on delete cascade,
  spieltag integer not null,
  note double precision,
  minuten_gespielt integer,
  unique (player_id, spieltag)
);

create table public.availability_status (
  id integer generated by default as identity primary key,
  player_id integer not null references public.player (id) on delete cascade,
  spieltag integer not null,
  status text not null,
  quelle text,
  aktualisiert_am timestamptz,
  unique (player_id, spieltag)
);

create table public.scrape_log (
  id integer generated by default as identity primary key,
  quelle text not null,
  zeitstempel timestamptz not null,
  status text not null,
  fehlermeldung text
);

create table public.squad_membership (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  player_id integer not null references public.player (id) on delete cascade,
  im_kader boolean not null default true,
  kaufpreis integer,
  hinzugefuegt_am date,
  unique (user_id, player_id)
);

create table public.manager_profile (
  id integer generated by default as identity primary key,
  user_id uuid not null unique references auth.users (id) on delete cascade,
  budget integer
);

create table public.competitor_squad (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  competitor_name text not null,
  player_id integer not null references public.player (id) on delete cascade,
  unique (user_id, competitor_name, player_id)
);

create index fixture_datum_idx on public.fixture (datum);
create index rating_history_player_idx on public.rating_history (player_id);
create index squad_membership_user_idx on public.squad_membership (user_id);

alter table public.player enable row level security;
alter table public.fixture enable row level security;
alter table public.value_history enable row level security;
alter table public.rating_history enable row level security;
alter table public.availability_status enable row level security;
alter table public.scrape_log enable row level security;
alter table public.squad_membership enable row level security;
alter table public.manager_profile enable row level security;
alter table public.competitor_squad enable row level security;

create policy player_read on public.player for select to authenticated using (true);
create policy fixture_read on public.fixture for select to authenticated using (true);
create policy value_history_read on public.value_history for select to authenticated using (true);
create policy rating_history_read on public.rating_history for select to authenticated using (true);
create policy availability_read on public.availability_status for select to authenticated using (true);

create policy squad_own on public.squad_membership
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy profile_own on public.manager_profile
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create policy competitor_own on public.competitor_squad
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

grant usage on schema public to authenticated;
grant select on public.player, public.fixture, public.value_history, public.rating_history, public.availability_status to authenticated;
grant select, insert, update, delete on public.squad_membership, public.manager_profile, public.competitor_squad to authenticated;
grant usage, select on all sequences in schema public to authenticated;
